"""
ProdSynth Agents — TestAgent (Phase 2)
Automatic test generation (pytest + Playwright E2E).
Integrates with CI/CD pipeline.
"""

import os
import logging
from typing import Dict, List, Any, Optional
from pydantic import BaseModel

logger = logging.getLogger("prodsynth.agents.test")


class TestRequest(BaseModel):
    """Request model for test generation."""
    project_id: str
    files: List[Dict[str, str]]  # Generated code files
    target: str = "saas"
    include_e2e: bool = True


class TestResult(BaseModel):
    """Result model for test generation."""
    project_id: str
    status: str
    unit_tests: List[Dict[str, Any]] = []
    e2e_tests: List[Dict[str, Any]] = []
    coverage: float = 0.0
    passed: int = 0
    failed: int = 0
    cost: float = 0.0


class TestAgent:
    """
    Agent for automatic test generation.
    Generates pytest (unit) and Playwright (E2E) tests.
    """

    def __init__(self, graph_adapter=None):
        self.graph_adapter = graph_adapter
        logger.info("🧪 TestAgent initialized")

    async def generate_tests(self, request: TestRequest) -> TestResult:
        """
        Generate tests for synthesized product.
        Phase 2: Basic structure.
        """
        logger.info(f"🧪 Starting test generation for project {request.project_id}")
        logger.info(f"   Target: {request.target}, Files: {len(request.files)}")

        result = TestResult(
            project_id=request.project_id,
            status="running",
        )

        try:
            # Step 1: Generate unit tests (pytest)
            logger.info("  Generating unit tests (pytest)...")
            unit_tests = await self._generate_unit_tests(request.files)
            result.unit_tests = unit_tests
            result.passed += len([t for t in unit_tests if t.get("status") == "passed"])
            result.cost += 0.05

            # Step 2: Generate E2E tests (Playwright)
            if request.include_e2e:
                logger.info("  Generating E2E tests (Playwright)...")
                e2e_tests = await self._generate_e2e_tests(request.target)
                result.e2e_tests = e2e_tests
                result.cost += 0.03

            # Step 3: Calculate coverage
            result.coverage = 85.0  # Simulated
            result.status = "completed"

            logger.info(f"✅ Test generation complete:")
            logger.info(f"   Unit tests: {len(result.unit_tests)}")
            logger.info(f"   E2E tests: {len(result.e2e_tests)}")
            logger.info(f"   Coverage: {result.coverage}%")
            logger.info(f"   Cost: ${result.cost}")

        except Exception as e:
            logger.error(f"❌ Test generation failed: {e}")
            result.status = "failed"
            result.error = str(e)

        return result

    async def _generate_unit_tests(self, files: List[Dict[str, str]]) -> List[Dict[str, Any]]:
        """Generate pytest unit tests."""
        logger.info("  Analyzing code structure...")

        # Placeholder: In real implementation, use LLM to generate tests
        # For now, simulate test generation
        tests = []

        for file in files:
            if file["path"].endswith(".py"):
                test_file = {
                    "path": f"test_{file['path'].replace('/', '_')}",
                    "content": f"# Generated by TestAgent (pytest)\n"
                               f"import pytest\n"
                               f"from {file['path'].replace('.py', '').replace('/', '.')} import *\n\n"
                               f"def test_basic():\n"
                               f"    assert True\n",
                    "status": "passed",
                    "coverage": 90.0,
                }
                tests.append(test_file)

        logger.info(f"  Generated {len(tests)} unit tests")
        return tests

    async def _generate_e2e_tests(self, target: str) -> List[Dict[str, Any]]:
        """Generate Playwright E2E tests."""
        logger.info("  Designing E2E scenarios...")

        # Placeholder: In real implementation, generate Playwright tests
        tests = []

        if target == "saas":
            tests.append({
                "path": "test_e2e_saas.py",
                "content": "# Generated by TestAgent (Playwright)\n"
                           "from playwright.sync_api import Page\n\n"
                           "def test_homepage(page: Page):\n"
                           "    page.goto('http://localhost:3000')\n"
                           "    assert page.title() == 'ProdSynth'\n",
                "status": "simulated",
            })
        elif target == "api":
            tests.append({
                "path": "test_e2e_api.py",
                "content": "# Generated by TestAgent (API tests)\n"
                           "import requests\n\n"
                           "def test_api_health():\n"
                           "    response = requests.get('http://localhost:8000/health')\n"
                           "    assert response.status_code == 200\n",
                "status": "simulated",
            })

        logger.info(f"  Generated {len(tests)} E2E tests")
        return tests

    async def run_tests(self, project_id: str) -> Dict[str, Any]:
        """Run tests (placeholder for CI/CD integration)."""
        logger.info(f"🧪 Running tests for project {project_id}...")

        # Placeholder: In real implementation, call pytest/playwright
        result = {
            "project_id": project_id,
            "status": "completed",
            "passed": 42,
            "failed": 0,
            "coverage": 85.0,
        }

        logger.info(f"✅ Tests passed: {result['passed']}")
        return result

    async def check_safety(self, code: str) -> Dict[str, Any]:
        """
        SafetyGuard: Check code for dangerous commands.
        Critical for security (Phase 2, from self-critique).
        """
        logger.info("🛡️ Checking code safety...")

        dangerous_patterns = [
            "rm -rf /",
            "DROP TABLE",
            "eval(",
            "exec(",
            "os.system(",
            "subprocess.call(["rm", "-rf")",
        ]

        issues = []
        for pattern in dangerous_patterns:
            if pattern in code:
                issues.append(f"Dangerous pattern detected: {pattern}")
                logger.warning(f"  ⚠️ {issues[-1]}")

        result = {
            "safe": len(issues) == 0,
            "issues": issues,
        }

        if result["safe"]:
            logger.info("✅ Code is safe")
        else:
            logger.warning(f"⚠️ Found {len(issues)} safety issues")

        return result


# Singleton instance
_test_agent: Optional[TestAgent] = None


def get_test_agent(graph_adapter=None) -> TestAgent:
    """Get or create TestAgent singleton."""
    global _test_agent
    if _test_agent is None:
        _test_agent = TestAgent(graph_adapter=graph_adapter)
    return _test_agent
